### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ejlamarque** [Chrisjb/fploptimiser#2]
Hi Chris,
             First of all, thank you for your great job. 

Unfortunately when I am trying to install the package give me this error. Could you help me to deal with this, please?
In the meantime, I will try to run all functions manually one by one to see if I can make it work in the other way.

>   # install.packages("devtools")
> library(devtools)
Loading required package: usethis
>   # install.packages("devtools")
> library(usethis)
> library(devtools)
> devtools::install_github('Chrisjb/fploptimiser')
Downloading GitHub repo Chrisjb/fploptimiser@master
√  checking for file 'C:\Users\user\AppData\Local\Temp\RtmpWywc4I\remotes4188395029d1\Chrisjb-fploptimiser-f4410f4/DESCRIPTION' (501ms)
-  preparing 'FPLOptimiseR':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'FPLOptimiseR/data/gameweek_data.RData'
-  building 'FPLOptimiseR_0.1.0.tar.gz'
   
Installing package into ‘C:/Users/user/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'FPLOptimiseR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Joining, by = "id"
Error in ggplot(fd_summary, aes(gw, forcats::fct_rev(team_name))) : 
  could not find function "ggplot"
Error: unable to load R code in package 'FPLOptimiseR'
Execution halted
ERROR: lazy loading failed for package 'FPLOptimiseR'
* removing 'C:/Users/user/Documents/R/win-library/4.0/FPLOptimiseR'
Error: Failed to install 'FPLOptimiseR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/user/AppData/Local/Temp/RtmpWywc4I/file4188145c6df2/FPLOptimiseR_0.1.0.tar.gz’ had non-zero exit status

**Comment by Chrisjb** [comment]
Thanks for notifying me, I updated the package dependencies and the install now works for me. Can you check if it works for you?

**Comment by ejlamarque** [comment]
Hi Chris. Yes, it is working perfectly now. Thank you.

**Comment by ejlamarque** [comment]
Hi Chris

              Thank you for the update. It is working perfect now.

I would like to know if you already update the code for FPL 20/21? In case of not, it is something that you intend
To do or not?

Thank you again and mis respects, you made a nice peace of job.

Best regards.

Enrique



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Chrisjb** [comment]
@ejlamarque yes the data the functions pull in should always be the latest and once the new season kicks off, you should be able to set `year=2020` to pull in the new season's xg data from understat.

The API the functions currently call is now updated for 2020 prices and positions so should be useful for planning your team for the current season

**Comment by ejlamarque** [comment]
Thank you for your prompt answer. Great news!!

Because I can’t install to fploptimiser, I ran it all “manually” and I add a free variable in the formula in order to select and optimise the team even under other selection like, xPts, different forecast or even choose coefficients or whatever you like. Nice

Again, Thank you and congratulation, not only for the peace of code, more than anything  for share it!!

Enrique

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ejlamarque** [comment]
Hi Chris

              I am contacting you because I would like to kindly request if it is possible for you in very easy way do a code to download the historic xG and xA of each player in this season from the premier league on Understat? Do you think that it is something that you can and more important, want to do? Thank you for your time.

Best regards

Enrique

PS: I am not still ready to do this job.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Chrisjb** [comment]
Thanks, I had assumed setting 'year =2019' would fetch the previous season's data. It doesn't seem to do that correctly so i will take a look when I get time!

**Comment by ejlamarque** [comment]
Thank you Chris for even consider this.  Somebody said that a picture is worth by a thousands of worlds. Please find attached a picture with in yellow what I am looking for. This Is what I would like to fetch because under my knowledge and for what I hear around, from a some more people, the historical xG of the player (and xA) with the delta of the of actual xG and the historic delta with the actual delta  of xG  produce a much useful data than the actual one. Again. This is my appreciation. Unfortunately I am not ready (yet) to code in R something to fetch this info. I don’t know. Sometimes is easy if you know how and sometimes is difficult even if you know how.  I hope that now (with the picture) is more undestable the request.  Please, let me know if it is possible do something.  Thank you again.  Enrique  Sent from Mail for Windows 10 From: ChrisjbSent: 06 October 2020 11:54To: Chrisjb/fploptimiserCc: ejlamarque; MentionSubject: Re: [Chrisjb/fploptimiser] Install Error (#2) Thanks, I had assumed setting 'year =2019' would fetch the previous season's data. It doesn't seem to do that correctly so i will take a look when I get time!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com
